language: php

notifications:
  email: false

php:
  - 5.5

env:
    global:
      - TEST_PHP_ARGS="-q"
      - REPORT_EXIT_STATUS=1
      - BUILD_SCRIPT="make test"

matrix:
  include:
    # 'make test' always exits 0 PHP < 5.5
    - php: 5.3
      env: BUILD_SCRIPT="\$PHP_DIR/lib/php/build/run-tests.php extension/"
    - php: 5.4
      env: BUILD_SCRIPT="\$PHP_DIR/lib/php/build/run-tests.php extension/"

before_script:
  - cd extension
  - phpize
  - ./configure
  - make -j4
  - which php
  - export PHP_DIR=$(dirname $(dirname $(phpenv which php)))
  - echo $PHP_DIR
  - env
  - phpenv which php

script: eval $BUILD_SCRIPT
