language: php

php:
    - 5.3
    - 5.4
    - 5.5

notifications:
    email: false

env:
    global:
      - TEST_PHP_ARGS="-q"
      - REPORT_EXIT_STATUS=1

before_script:
    - cd extension
    - phpize
    - ./configure
    - make -j4

script: make test
