language: php

php:
    - 5.4

notifications:
    email: false

env:
    global:
      - TEST_PHP_ARGS="-q"

before_script:
    - cd extension
    - phpize
    - ./configure
    - make -j4

script: make test
