language: php

notifications:
  email: false

php:
  - 5.5

env:
    global:
      - TEST_PHP_ARGS="-q"
      - REPORT_EXIT_STATUS=1
      - BUILD_SCRIPT="make test"

matrix:
  include:
    # 'make test' always exits 0 PHP < 5.5
    - php: 5.3
      env: BUILD_SCRIPT="which php; run-tests.php"
    - php: 5.4
      env: BUILD_SCRIPT="which php; run-tests.php"

before_script:
  - cd extension
  - phpize
  - ./configure
  - make -j4

script: $BUILD_SCRIPT
